### PR TITLE
Upgrade to Gradle 4.8.1

### PR DESCRIPTION
**Pull request by valfirst**

### CODE REVIEW

**Comment by valfirst** [comment]
@wakaleo please take a look

**Comment by wakaleo** [comment]
The latest version of Gradle is 4.10 or so, is there a reason you preferred 4.8.1?

**Comment by valfirst** [comment]
it's old PR, I tested Gradle 4.8 and it supports JDK 11 (current is 4.6, and it doesn't recognize JDK 11 as runtime), Gradle 4.10 will require additional round of testing

**Comment by wakaleo** [comment]
serenity-core is on 4.9, which works with JDK 11.

**Comment by valfirst** [comment]
`serenity-jbehave` uses Gradle 4.6 ([gradle-wrapper.properties#L3](https://github.com/serenity-bdd/serenity-jbehave/blob/master/gradle/wrapper/gradle-wrapper.properties#L3)) which doesn't work with JDK 11. I faced with this problem while building the project, I switched to this old PR and built the project again, build was successful, and I pinged you.
Please feel free to close  this PR and upgrade the project to Gradle 4.10.

**Comment by wakaleo** [comment]
Thanks for pointing it out - I will include the change in the next version; if you want to update the PR I will merge it in so that you get credit for the suggestion.

**Comment by valfirst** [comment]
Superseded by #221

**Pull request closed without merging**
