### PR TITLE
Remove unused file: gradle-wrapper.properties

### PR DESCRIPTION
**Pull request by valfirst**

### CODE REVIEW

**Comment by valfirst** [comment]
@wakaleo do you plan to maintain this project?

**Comment by wakaleo** [comment]
It's not a high priority.

**Comment by valfirst** [comment]
@wakaleo do you plan at least to review/merge PRs? I'm asking to understand whether it's worth contributing

**Comment by wakaleo** [comment]
I will review PRs. However the project needs to be migrated away from Bintray to Maven Central, and potentially from Gradle to Maven, before a new release can be deployed, and I don't know when this will happen.

**Pull request merged**
